version: "2"
services:
  web:
    build: ./packages/api
    ports:
      - "3000:3000"
    links:
      - urldb
  mongo-seed:
      environment:
        - MONGO_HOST=streamdb
        - MONGO_PORT=27017
      image: mongo
      links: 
        - urldb 
      volumes: 
        - ./data:/data
      command:
              "mongoimport --host urldb --port 27017 --db test --mode upsert --type json --file /data/init.json --jsonArray --db urls --collection shortenedUrls"
  urldb:
    image: mongo
    ports:
      - "27017:27017"